config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save
    redirect_to articles_path(@article)
  end

  def edit
  end

  def update
    @article.update(article_params)
    redirect_to articles_path(@article)
  end

  def destroy

    @article.destroy
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :content)
  end

  def set_article
    @article = Article.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= simple_form_for(@article) do |f| %>
  <%= f.input :title %>
  <%= f.input :content %>
  <%= f.submit %>
<% end %>

app/views/articles/edit.html.erb
<h1>Hi</h1>

<%= render "form", article: @article  %>

<button type="button" class="btn btn-outline-primary"><%= link_to 'Back', articles_path %></button>

app/views/articles/index.html.erb
<h1>wikinimous</h1>
<h5><%= link_to 'New article', '/articles/new' %></h5>

<% @articles.each_with_index do |article, index| %>
  <ul class="list-group">
    <li class="list-group-item"><%= link_to article.title, article_path(article) %></li>
  </ul>

<% end %>

app/views/articles/new.html.erb
<h1>Hello</h1>

<%= render "form", article: @article  %>

<button type="button" class="btn btn-outline-primary"><%= link_to 'Back', articles_path %></button>

app/views/articles/show.html.erb
<h1><%= @article.title  %></h1>
<p><%= @article.content %></p>
<button type="button" class="btn btn-outline-secondary"><%= link_to 'Edit', edit_article_path %></button>
<button type="button" class="btn btn-outline-primary"><%= link_to 'Back', articles_path %></button>
<button type="button" class="btn btn-outline-danger"><%= link_to 'Delete', article_path(@article), method: :delete, data: { confirm: 'Delete article?' } %></button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>